services:
  todo-frontend:
    image: todo-frontend
    build:
      context: ./todo-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/todo-app/todo-frontend
    ports:
      - 3001:3000
    container_name: todo-frontend
    environment:
    - REACT_APP_BACKEND_URL=http://localhost:3000
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-frontend